apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: playground
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx
        type: webserver
    spec:
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: IfNotPresent