apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    type: webserver
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  - envFrom:
    - configMapRef:
        name: my-config3
